<a href="https://colab.research.google.com/github/namangoyal176-10/Data-Science/blob/main/class6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import pandas as pd

dct ={
    'name': ['tom','nick','krish'],
    'age': ['20','21','40'],
}
#we use the display to print
df = pd.DataFrame(dct,index=['a','b','c'])
display(df)

    name age
a    tom  20
b   nick  21
c  krish  40

In [85]:
df = pd.read_csv('student_data.csv')
#head use to provide that number of line
display(df.head(3))

df.tail(3) #display last values

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.0,Placed
1,4,69,5,3,8,56,100.0,Placed
2,11,60,7,6,10,45,100.0,Placed

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [86]:
#meta data is about a data
df.info()
#25% > is a first quartile
#50% > is a second quartile
#75% > is a third quartile
df.columns
df.index
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [87]:
df = pd.read_csv('student_data.csv')
df[['internet_usage']]
df.study_hours

0        7
1        4
2       11
3        8
4        5
        ..
9995     2
9996     7
9997    10
9998    10
9999     2
Name: study_hours, Length: 10000, dtype: int64

In [88]:
display(df.iloc[0:5])
#loc works on condition and iloc works on row printing
df.loc[df['study_hours'] == 11]
df2= df.loc[df['study_hours']==11]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [89]:
df2= df.loc[df['study_hours']==11].iloc[1]
display(df2)
#this use to add new coloumn
df["age"] = 20
df
df = df.rename(columns = {'assignments_completed':'assign_completed'},inplace = True)
df

study_hours                  11
attendance                   77
sleep_hours                   4
internet_usage                9
assignments_completed        15
previous_score               69
exam_score                100.0
placement_status         Placed
Name: 9, dtype: object

In [90]:
# df[df['study_hours']>4]

In [92]:
#removes missing values
import pandas as pd
df = pd.read_csv('student_data.csv')

In [93]:
df = df.drop(2,axis =0)
display(df)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed